version: "3.9"
services:
  database:
    image: mongo
    container_name: mern-database
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - mern-network

  backend:
    build:
      context: ./backend
      dockerfile: DockerFile
    container_name: mern-backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    command: npm start
    networks:
      - mern-network
    environment:
      - MONGO_URI=mongodb://database:27017/mernDB

  frontend:
    build:
      context: ./frontend
      dockerfile: DockerFile
    container_name: mern-frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app

    networks:
      - mern-network

networks:
  mern-network:

volumes:
  mongo-data:
